name: release
run-name: >-
  ${{
    (
      (
        github.event_name == 'workflow_dispatch' &&
        github.ref_name == github.event.repository.default_branch
      ) ||
      (
        github.event_name == 'push' &&
        github.ref_name == 'beta'
      )
    ) && 'Release publish' || 'Release preview'
  }} - ${{ github.ref_name }}

on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    environment: npm
    env:
      NPM_CONFIG_PROVENANCE: true
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    defaults:
      run:
        shell: nix develop --command bash --noprofile --norc -eo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check
        run: pnpm run check

      - name: Release preview
        if: >-
          github.ref_name == github.event.repository.default_branch &&
          github.event_name == 'push'
        run: pnpm exec semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish beta release
        if: github.ref_name == 'beta' && github.event_name == 'push'
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: >-
          github.ref_name == github.event.repository.default_branch &&
          github.event_name == 'workflow_dispatch'
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
